---

deployment:
  name: encryption-service
  image: vpnbeast/encryption-service:1.0.22
  replicaCount: 1
  serverPort: 8085
  metricsPort: 8086
  managementEndpoint: /health/ping
  ingressEndpoint: /encryption-service
  environment:
    timezone: Europe/Istanbul
    readTimeoutSeconds: 10
    writeTimeoutSeconds: 10

ingress:
  enabled: false
